name: workflow event example
on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.11","3.12"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print entry
        run: echo "Matrix job for python ${{ matrix.python-version }}"
